nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.7.0.cjs

packageExtensions:
  'eslint-config-airbnb-typescript@*':
    peerDependencies:
      eslint-plugin-import: '*'
  '@chromatic-com/storybook@*':
    peerDependencies:
      react: '^16.3.0 || ^17.0.1 || ^18.0.0'
  '@storybook/addon-onboarding@*':
    peerDependencies:
      react: '^16.3.0 || ^17.0.1 || ^18.0.0'
