import { Sidebar } from '@/container/Sidebar/Sidebar';
import { QueryProvider } from '@/lib';
import clsx from 'clsx';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { QueryProvider } from '@/lib';
import './globals.css';
import { Sidebar } from '@/container/Sidebar/Sidebar';
import clsx from 'clsx';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '뽀각',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, 'flex')}>
        <Sidebar />
        {/* FIXME: */}
        <div className="flex-grow">
          <QueryProvider>{children}</QueryProvider>
        </div>
      </body>
    </html>
  );
}
